In [18]:
import numpy as np
np.array([3.14, 4, 2, 3])
# If we want to explicitly set the data type of the resulting array, we can use the dtype keyword:
np.array([1, 2, 3, 4], dtype='float32')


array([1., 2., 3., 4.], dtype=float32)

Finally, unlike Python lists, NumPy arrays can explicitly be multi-dimensional; here's one way of initializing a multidimensional array using a list of lists:

In [31]:
np.array([ range(i,i+1) for i in [1,2,3]])

array([[1],
       [2],
       [3]])

In [32]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [33]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [35]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 1.52963413, -0.18450113,  0.90483678],
       [-0.18008154,  1.36968863,  0.49113907],
       [ 1.8685692 , -0.06431403,  1.53968392]])

In [36]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[6, 8, 9],
       [7, 8, 9],
       [5, 5, 2]])

In [37]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3,4,5))  # Three-dimensional array
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [49]:
print("x2 ndim: ", x2.ndim) # (the number of dimensions)
print("x2 shape:", x2.shape)#(the size of each dimension)
print("x2 size: ", x2.size) #(the total size of the array)
x2

x2 ndim:  2
x2 shape: (3, 4)
x2 size:  12


array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

# eğer numpy dizisindeki tüm elemanlar int ise ve biz float bir sayı eklersek, virgülden sonraki kısım kesilir.


In [53]:
x2

array([[9, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [52]:
x2[0,0]=9
x2

array([[9, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [56]:
#Finally, subarray dimensions can even be reversed together:
x2[::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 9]])

# Fancy Indexing

In [66]:
yeniListe=[[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19]]
yeniMatrix=np.array(yeniListe)
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [67]:
yeniMatrix[[1,2,3]] # index yerine liste vererek yeni bir matrix oluşturuyor

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Operasyonlar

In [69]:
yeniBirDizi= np.random.randint(1,100,20) # 1'den 100'e kadar toplamda 20 sayı
yeniBirDizi

array([95,  1, 51, 37, 35, 49, 94,  4, 99, 43, 78, 22, 74,  1, 11, 44, 59,
       24, 60,  3])

In [81]:
# Büyüktür operasyonu ile sayıların büyüklük durumuna göre True False çıktısı
# vermesini sağlar
yeniBirDizi > 24 
sonucDizisi = yeniBirDizi > 24 
print(yeniBirDizi>24)
# Dizinin kendisine index olarak eşitsizlik koyulursa bu bilgiyi sağlayan
# değerlerle yeni bir dizi oluşturulur.
print(yeniBirDizi[sonucDizisi])

[ True False  True  True  True  True  True False  True  True  True False
  True False False  True  True False  True False]
[95 51 37 35 49 94 99 43 78 74 44 59 60]


# Toplama ve Çıkarma


In [2]:
# numpy dizilerinde matematiksel işlemler aynı indexlerin toplanması, çarpılması
# ile olur
import numpy as np
i = np.array([0,1,2,3,4,5])
y= np.array([6,7,8,9,9,10])
i+y

array([ 6,  8, 10, 12, 13, 15])

In [3]:
i.max()

5

In [4]:
np.sqrt(i)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

# Arrayları birleştirme ve ayırma


Birleştirme

In [5]:
x= np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [6]:
#You can also concatenate 2-D arrays at once:
grid = np.array([[1,2,3],
                [4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [7]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3, x4 = np.split(x, [2,5,7])
print(x1, x2, x3, x4)

[1 2] [ 3 99 99] [3 2] [1]


In [9]:
#Vertical split
grid = np.arange(16).reshape((4, 4))
print(grid)
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [10]:
#Horizontal split
grid = np.arange(16).reshape((4, 4))
print(grid)
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Outputu Belirlemek

In [12]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x,10,out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [13]:
# Toplam 
x=np.arange(6)
np.add.reduce(x)

15

In [14]:
# Toplayarak Gitmek
np.add.accumulate(x)

array([ 0,  1,  3,  6, 10, 15], dtype=int32)

In [15]:
# Listeyi Sıralamak
x= np.array([3,2,1,10,7,11,8,0])
np.sort(x)

array([ 0,  1,  2,  3,  7,  8, 10, 11])