# Operasyonlar

In [3]:
import numpy as np
benimDizim = np.arange(0,15)
benimDizim
benimDizim[5]

5

In [6]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

# 3'den 8'e kadar olan elemanları -5 ile değiştirdi.
# bu eşitlik ile benimDizim değiştirilmiştir.

In [24]:
benimDizim[3:8]=5
benimDizim

array([ 0,  1,  2,  5,  5,  5,  5,  5,  8,  9, 10, 11, 12, 13, 14])

# Bu aralıktaki dizi bilgisini yeni bir dizi olarak
## tanımlayabiliriz.

In [25]:
yeniDizi=benimDizim[3:8]
yeniDizi

array([5, 5, 5, 5, 5])

# Büyük diziden küçük dizi oluşturup içindeki elemanların hepsini 700 yapıyoruz
# En önemli şey ise slicingDizi'ni değiştirmemiz üzerine baskaDizi de değişir

In [26]:
baskaDizi= np.arange(0,24)
slicingDizisi=baskaDizi[4:9]
slicingDizisi[:]=700
slicingDizisi

array([700, 700, 700, 700, 700])

In [27]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

# Oluşturulan slicingDizi üstündeki değişikliklerin asıl diziyi etkilememesi için copy methodu kullanılmalı


In [28]:
ornekDizi = np.arange(0,24)
ornekDiziKopyasi=ornekDizi.copy()
ornekDiziKopyaSlicing=ornekDiziKopyasi[3:6]
ornekDiziKopyaSlicing[:]=800
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

# Matrisler

In [29]:
benimListem = [[10,20,30],[40,50,60],[70,80,90]]
benimMatrixDizim= np.array(benimListem)
benimMatrixDizim

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [30]:
benimMatrixDizim[0]

array([10, 20, 30])

In [31]:
benimMatrixDizim[1][2]

60

In [33]:
# bu gösterim ile yukarıdaki gösterim aynıdır
benimMatrixDizim[1,2]

60

# 0. satırdan başla, 2. sütundakileri yazdır demektir

In [46]:
benimMatrixDizim[0: , 2]

array([30, 60, 90])

# 2. sütunu bastır demektir

In [47]:
benimMatrixDizim[0: , 1]

array([20, 50, 80])

# 0. satırdan başla ve sona kadar git, 1. sütundan başla sona kadar git demektir

In [48]:
benimMatrixDizim[ 2: , 0:]

array([[70, 80, 90]])

# Deneme

In [ ]:
yeniListe=range(0,20)

for i in range(0,5)